# Workflow created by GitHub Copilot Chat Assistant — original author: ELF-RC
name: Build Kernel
on:
  workflow_dispatch:
    inputs:
        LOCALVERSIONNAME:
            description: 'Kernel Local Version Name'
            required: true
            default: '' 

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-24.04
    steps:

      - name: Set Beijing Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Set SWAP To 5GiB
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: Clean Useless Files
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
      - name: Get Branch Name
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Initialize Compilation Environment
        run: |
          sudo apt-get update
          sudo apt-get install build-essential lld libssl-dev libelf-dev flex bison bc curl git zip llvm -y
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch-names.outputs.current_branch }}

      - name: Get Toolchain
        run: |
          git clone https://github.com/ELF-RC/android_kernel4x_tools.git tooltmp
          
      - name: Build Kernel
        run: |
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
          export PATH="$GITHUB_WORKSPACE/tooltmp/clang/host/linux-x86/clang-r428724/bin:$PATH"
          make -j$(nproc --all) O=out ARCH=arm64 CC=clang CROSS_COMPILE=$GITHUB_WORKSPACE/tooltmp/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu- CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/tooltmp/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi- AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf OBJSIZE=llvm-size STRIP=llvm-strip HOSTCC=clang HOSTCXX=clang++ LLVM_AR=llvm-ar LLVM_DIS=llvm-dis cannon_defconfig
          make -j$(nproc --all) O=out ARCH=arm64 CC=clang CROSS_COMPILE=$GITHUB_WORKSPACE/tooltmp/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu- CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/tooltmp/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi- AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf OBJSIZE=llvm-size STRIP=llvm-strip HOSTCC=clang HOSTCXX=clang++ LLVM_AR=llvm-ar LLVM_DIS=llvm-dis

      - name: Pack Kernel with AnyKernel3
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3 -b master AK3
          cp out/arch/arm64/boot/Image.gz-dtb AK3/
          cd AK3
          sed -i 's|kernel.string=.*|kernel.string=Xiaomi Custom Kernel By ELF-RC|' anykernel.sh
          sed -i 's|device.name1=.*|device.name1=cannon|' anykernel.sh
          sed -i 's|device.name2=.*|device.name2=cannong|' anykernel.sh
          sed -i 's|BLOCK=.*|BLOCK=/dev/block/by-name/boot;|' anykernel.sh
          rm -rf .git README.md LICENSE

      - name: Upload Kernel Package
        uses: actions/upload-artifact@v4
        with:
          name: cannon_customKernel_${{ github.event.inputs.LOCALVERSIONNAME }}_${{ github.actor }}
          path: AK3/
